/*
	Generated by tools/pipesim/gen_optable.py - do not edit by hand.

	Per-opcode pipeline data for the SH4 cycle model.

	issue / latency / unit / exType are taken from flycast's own
	sh4_opcodelistentry table, which already carries all four for every
	opcode; exType is the execution-pattern number from figure 8.2 of the
	SH4 program manual.

	reads / writes are derived from the opcode's operand format and
	cross-checked against skmp's independently written SH-4 pipeline
	simulator. Where the two disagree the disagreement is recorded in
	docs/cachesim/pipesim_notes.md rather than silently resolved.

	RN/RM/FN/FM and friends are symbolic: they name an encoding field, not
	a register, and are resolved against the actual opcode by regsFor().
*/
#pragma once
#include "types.h"
#include "hw/sh4/sh4_opcode_list.h"

namespace pipesim
{

// Symbolic operand slots. RN/RM refer to flycast's own encoding fields
// (bits 8-11 and 4-7), which is not always the letter the manual uses for
// the same field.
enum RegSym : u32
{
	SYM_RN       = 1u << 0,
	SYM_RM       = 1u << 1,
	SYM_R0       = 1u << 2,
	SYM_RBANK    = 1u << 3,
	SYM_GBR      = 1u << 4,
	SYM_SR       = 1u << 5,
	SYM_SSR      = 1u << 6,
	SYM_SPC      = 1u << 7,
	SYM_VBR      = 1u << 8,
	SYM_DBR      = 1u << 9,
	SYM_SGR      = 1u << 10,
	SYM_PR       = 1u << 11,
	SYM_MACH     = 1u << 12,
	SYM_MACL     = 1u << 13,
	SYM_FPUL     = 1u << 14,
	SYM_FPSCR    = 1u << 15,
	SYM_T        = 1u << 16,
	SYM_FN       = 1u << 17,
	SYM_FM       = 1u << 18,
	SYM_F0       = 1u << 19,
	SYM_DN       = 1u << 20,
	SYM_FVN      = 1u << 21,
	SYM_FVM      = 1u << 22,
	SYM_XMTRX    = 1u << 23,
};

struct OpInfo
{
	u16 mask;
	u16 rez;
	u8 issue;
	u8 latency;
	sh4_eu unit;
	u8 exType;
	u32 reads;
	u32 writes;
};

static const OpInfo opInfoTable[] = {
	{ 0xF0FF, 0x0023, 2,  3, CO,  4, 0x000001u, 0x000000u }, // braf <REG_N>
	{ 0xF0FF, 0x0003, 2,  3, CO, 24, 0x000001u, 0x000000u }, // bsrf <REG_N>
	{ 0xF0FF, 0x00C3, 1,  4, LS, 12, 0x000005u, 0x000000u }, // movca.l R0, @<REG_N>
	{ 0xF0FF, 0x0093, 1,  2, LS, 10, 0x000001u, 0x000000u }, // ocbi @<REG_N>
	{ 0xF0FF, 0x00A3, 1,  3, LS, 11, 0x000001u, 0x000000u }, // ocbp @<REG_N>
	{ 0xF0FF, 0x00B3, 1,  3, LS, 11, 0x000001u, 0x000000u }, // ocbwb @<REG_N>
	{ 0xF0FF, 0x0083, 1,  1, LS,  2, 0x000001u, 0x000000u }, // pref @<REG_N>
	{ 0xF00F, 0x0007, 2,  4, CO, 34, 0x000003u, 0x002000u }, // mul.l <REG_M>,<REG_N>
	{ 0xFFFF, 0x0028, 1,  3, CO, 28, 0x000000u, 0x003000u }, // clrmac
	{ 0xFFFF, 0x0048, 1,  1, CO,  1, 0x000000u, 0x000000u }, // clrs
	{ 0xFFFF, 0x0008, 1,  1, MT,  1, 0x000000u, 0x010000u }, // clrt
	{ 0xFFFF, 0x0038, 1,  1, CO,  2, 0x000000u, 0x000000u }, // ldtlb
	{ 0xFFFF, 0x0058, 1,  1, CO,  1, 0x000000u, 0x000000u }, // sets
	{ 0xFFFF, 0x0018, 1,  1, MT,  1, 0x000000u, 0x010000u }, // sett
	{ 0xFFFF, 0x0019, 1,  1, EX,  1, 0x000000u, 0x010000u }, // div0u
	{ 0xF0FF, 0x0029, 1,  1, EX,  1, 0x010000u, 0x000001u }, // movt <REG_N>
	{ 0xFFFF, 0x0009, 1,  0, MT,  1, 0x000000u, 0x000000u }, // nop
	{ 0xFFFF, 0x0000, 1,  0, MT,  1, 0x000000u, 0x000000u }, // nop0
	{ 0xFFFF, 0x002B, 5,  5, CO,  8, 0x000000u, 0x000000u }, // rte
	{ 0xFFFF, 0x000B, 2,  3, CO,  4, 0x000000u, 0x000000u }, // rts
	{ 0xFFFF, 0x001B, 4,  4, CO,  9, 0x000000u, 0x000000u }, // sleep
	{ 0xF00F, 0x000F, 2,  4, CO, 35, 0x000003u, 0x003003u }, // mac.l @<REG_M>+,@<REG_N>+
	{ 0xF00F, 0x2007, 1,  1, EX,  1, 0x000003u, 0x010000u }, // div0s <REG_M>,<REG_N>
	{ 0xF00F, 0x2008, 1,  1, MT,  1, 0x000003u, 0x010000u }, // tst <REG_M>,<REG_N>
	{ 0xF00F, 0x2009, 1,  1, EX,  1, 0x000003u, 0x000001u }, // and <REG_M>,<REG_N>
	{ 0xF00F, 0x200A, 1,  1, EX,  1, 0x000003u, 0x000001u }, // xor <REG_M>,<REG_N>
	{ 0xF00F, 0x200B, 1,  1, EX,  1, 0x000003u, 0x000001u }, // or <REG_M>,<REG_N>
	{ 0xF00F, 0x200C, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/str <REG_M>,<REG_N>
	{ 0xF00F, 0x200D, 1,  1, EX,  1, 0x000003u, 0x000001u }, // xtrct <REG_M>,<REG_N>
	{ 0xF00F, 0x200E, 2,  4, CO, 34, 0x000003u, 0x002000u }, // mulu.w <REG_M>,<REG_N>
	{ 0xF00F, 0x200F, 2,  4, CO, 34, 0x000003u, 0x002000u }, // muls.w <REG_M>,<REG_N>
	{ 0xF00F, 0x3000, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/eq <REG_M>,<REG_N>
	{ 0xF00F, 0x3002, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/hs <REG_M>,<REG_N>
	{ 0xF00F, 0x3003, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/ge <REG_M>,<REG_N>
	{ 0xF00F, 0x3004, 1,  1, EX,  1, 0x010003u, 0x010001u }, // div1 <REG_M>,<REG_N>
	{ 0xF00F, 0x3005, 2,  4, CO, 34, 0x000003u, 0x003000u }, // dmulu.l <REG_M>,<REG_N>
	{ 0xF00F, 0x3006, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/hi <REG_M>,<REG_N>
	{ 0xF00F, 0x3007, 1,  1, MT,  1, 0x000003u, 0x010000u }, // cmp/gt <REG_M>,<REG_N>
	{ 0xF00F, 0x3008, 1,  1, EX,  1, 0x000003u, 0x000001u }, // sub <REG_M>,<REG_N>
	{ 0xF00F, 0x300A, 1,  1, EX,  1, 0x010003u, 0x010001u }, // subc <REG_M>,<REG_N>
	{ 0xF00F, 0x300B, 1,  1, EX,  1, 0x000003u, 0x010001u }, // subv <REG_M>,<REG_N>
	{ 0xF00F, 0x300C, 1,  1, EX,  1, 0x000003u, 0x000001u }, // add <REG_M>,<REG_N>
	{ 0xF00F, 0x300D, 2,  4, CO, 34, 0x000003u, 0x003000u }, // dmuls.l <REG_M>,<REG_N>
	{ 0xF00F, 0x300E, 1,  1, EX,  1, 0x010003u, 0x010001u }, // addc <REG_M>,<REG_N>
	{ 0xF00F, 0x300F, 1,  1, EX,  1, 0x000003u, 0x010001u }, // addv <REG_M>,<REG_N>
	{ 0xF00F, 0x0004, 1,  1, LS,  2, 0x000007u, 0x000000u }, // mov.b <REG_M>,@(R0,<REG_N>)
	{ 0xF00F, 0x0005, 1,  1, LS,  2, 0x000007u, 0x000000u }, // mov.w <REG_M>,@(R0,<REG_N>)
	{ 0xF00F, 0x0006, 1,  1, LS,  2, 0x000007u, 0x000000u }, // mov.l <REG_M>,@(R0,<REG_N>)
	{ 0xF00F, 0x000C, 1,  2, LS,  2, 0x000006u, 0x000001u }, // mov.b @(R0,<REG_M>),<REG_N>
	{ 0xF00F, 0x000D, 1,  2, LS,  2, 0x000006u, 0x000001u }, // mov.w @(R0,<REG_M>),<REG_N>
	{ 0xF00F, 0x000E, 1,  2, LS,  2, 0x000006u, 0x000001u }, // mov.l @(R0,<REG_M>),<REG_N>
	{ 0xF000, 0x1000, 1,  1, LS,  2, 0x000003u, 0x000000u }, // mov.l <REG_M>,@(<disp4dw>,<REG_N>)
	{ 0xF000, 0x5000, 1,  2, LS,  2, 0x000002u, 0x000001u }, // mov.l @(<disp4dw>,<REG_M>),<REG_N>
	{ 0xF00F, 0x2000, 1,  1, LS,  2, 0x000003u, 0x000000u }, // mov.b <REG_M>,@<REG_N>
	{ 0xF00F, 0x2001, 1,  1, LS,  2, 0x000003u, 0x000000u }, // mov.w <REG_M>,@<REG_N>
	{ 0xF00F, 0x2002, 1,  1, LS,  2, 0x000003u, 0x000000u }, // mov.l <REG_M>,@<REG_N>
	{ 0xF00F, 0x6000, 1,  2, LS,  2, 0x000002u, 0x000001u }, // mov.b @<REG_M>,<REG_N>
	{ 0xF00F, 0x6001, 1,  2, LS,  2, 0x000002u, 0x000001u }, // mov.w @<REG_M>,<REG_N>
	{ 0xF00F, 0x6002, 1,  2, LS,  2, 0x000002u, 0x000001u }, // mov.l @<REG_M>,<REG_N>
	{ 0xF00F, 0x2004, 1,  1, LS,  2, 0x000003u, 0x000001u }, // mov.b <REG_M>,@-<REG_N>
	{ 0xF00F, 0x2005, 1,  1, LS,  2, 0x000003u, 0x000001u }, // mov.w <REG_M>,@-<REG_N>
	{ 0xF00F, 0x2006, 1,  1, LS,  2, 0x000003u, 0x000001u }, // mov.l <REG_M>,@-<REG_N>
	{ 0xF00F, 0x6004, 1,  2, LS,  2, 0x000002u, 0x000003u }, // mov.b @<REG_M>+,<REG_N>
	{ 0xF00F, 0x6005, 1,  2, LS,  2, 0x000002u, 0x000003u }, // mov.w @<REG_M>+,<REG_N>
	{ 0xF00F, 0x6006, 1,  2, LS,  2, 0x000002u, 0x000003u }, // mov.l @<REG_M>+,<REG_N>
	{ 0xFF00, 0x8000, 1,  1, LS,  2, 0x000006u, 0x000000u }, // mov.b R0,@(<disp4b>,<REG_M>)
	{ 0xFF00, 0x8100, 1,  1, LS,  2, 0x000006u, 0x000000u }, // mov.w R0,@(<disp4w>,<REG_M>)
	{ 0xFF00, 0x8400, 1,  2, LS,  2, 0x000002u, 0x000004u }, // mov.b @(<disp4b>,<REG_M>),R0
	{ 0xFF00, 0x8500, 1,  2, LS,  2, 0x000002u, 0x000004u }, // mov.w @(<disp4w>,<REG_M>),R0
	{ 0xF000, 0x9000, 1,  2, LS,  2, 0x000000u, 0x000001u }, // mov.w @(<PCdisp8w>),<REG_N>
	{ 0xFF00, 0xC000, 1,  1, LS,  3, 0x000014u, 0x000000u }, // mov.b R0,@(<disp8b>,GBR)
	{ 0xFF00, 0xC100, 1,  1, LS,  3, 0x000014u, 0x000000u }, // mov.w R0,@(<disp8w>,GBR)
	{ 0xFF00, 0xC200, 1,  1, LS,  3, 0x000014u, 0x000000u }, // mov.l R0,@(<disp8dw>,GBR)
	{ 0xFF00, 0xC400, 1,  2, LS,  3, 0x000010u, 0x000004u }, // mov.b @(<GBRdisp8b>),R0
	{ 0xFF00, 0xC500, 1,  2, LS,  3, 0x000010u, 0x000004u }, // mov.w @(<GBRdisp8w>),R0
	{ 0xFF00, 0xC600, 1,  2, LS,  3, 0x000010u, 0x000004u }, // mov.l @(<GBRdisp8dw>),R0
	{ 0xF000, 0xD000, 1,  2, LS,  2, 0x000000u, 0x000001u }, // mov.l @(<PCdisp8d>),<REG_N>
	{ 0xF00F, 0x6003, 1,  0, MT,  1, 0x000002u, 0x000001u }, // mov <REG_M>,<REG_N>
	{ 0xFF00, 0xC700, 1,  1, EX,  1, 0x000000u, 0x000004u }, // mova @(<PCdisp8d>),R0
	{ 0xF000, 0xE000, 1,  1, EX,  1, 0x000000u, 0x000001u }, // mov #<simm8hex>,<REG_N>
	{ 0xF0FF, 0x4052, 1,  1, CO,  2, 0x004001u, 0x000001u }, // sts.l FPUL,@-<REG_N>
	{ 0xF0FF, 0x4062, 1,  1, CO,  2, 0x008001u, 0x000001u }, // sts.l FPSCR,@-<REG_N>
	{ 0xF0FF, 0x4002, 1,  1, CO, 31, 0x001001u, 0x000001u }, // sts.l MACH,@-<REG_N>
	{ 0xF0FF, 0x4012, 1,  1, CO, 31, 0x002001u, 0x000001u }, // sts.l MACL,@-<REG_N>
	{ 0xF0FF, 0x4022, 2,  2, CO, 27, 0x000801u, 0x000001u }, // sts.l PR,@-<REG_N>
	{ 0xF0FF, 0x40F2, 2,  2, CO, 22, 0x000201u, 0x000001u }, // stc.l DBR,@-<REG_N>
	{ 0xF0FF, 0x4032, 3,  3, CO, 23, 0x000401u, 0x000001u }, // stc.l SGR,@-<REG_N>
	{ 0xF0FF, 0x4003, 2,  2, CO, 22, 0x000021u, 0x000001u }, // stc.l SR,@-<REG_N>
	{ 0xF0FF, 0x4013, 2,  2, CO, 22, 0x000011u, 0x000001u }, // stc.l GBR,@-<REG_N>
	{ 0xF0FF, 0x4023, 2,  2, CO, 22, 0x000101u, 0x000001u }, // stc.l VBR,@-<REG_N>
	{ 0xF0FF, 0x4033, 2,  2, CO, 22, 0x000041u, 0x000001u }, // stc.l SSR,@-<REG_N>
	{ 0xF0FF, 0x4043, 2,  2, CO, 22, 0x000081u, 0x000001u }, // stc.l SPC,@-<REG_N>
	{ 0xF08F, 0x4083, 2,  2, CO, 22, 0x000009u, 0x000001u }, // stc <RM_BANK>,@-<REG_N>
	{ 0xF0FF, 0x4006, 1,  3, CO, 29, 0x000001u, 0x001001u }, // lds.l @<REG_N>+,MACH
	{ 0xF0FF, 0x4016, 1,  3, CO, 29, 0x000001u, 0x002001u }, // lds.l @<REG_N>+,MAC
	{ 0xF0FF, 0x4026, 2,  3, CO, 25, 0x000001u, 0x000801u }, // lds.l @<REG_N>+,PR
	{ 0xF0FF, 0x4036, 3,  3, CO, 18, 0x000001u, 0x000401u }, // ldc.l @<REG_N>+,SGR
	{ 0xF0FF, 0x4056, 1,  2, CO,  2, 0x000001u, 0x004001u }, // lds.l @<REG_N>+,FPUL
	{ 0xF0FF, 0x4066, 1,  4, CO, 33, 0x000001u, 0x008001u }, // lds.l @<REG_N>+,FPSCR
	{ 0xF0FF, 0x40F6, 1,  3, CO, 17, 0x000001u, 0x000201u }, // ldc.l @<REG_N>+,DBR
	{ 0xF0FF, 0x4007, 4,  4, CO, 19, 0x000001u, 0x000021u }, // ldc.l @<REG_N>+,SR
	{ 0xF0FF, 0x4017, 3,  3, CO, 18, 0x000001u, 0x000011u }, // ldc.l @<REG_N>+,GBR
	{ 0xF0FF, 0x4027, 1,  3, CO, 17, 0x000001u, 0x000101u }, // ldc.l @<REG_N>+,VBR
	{ 0xF0FF, 0x4037, 1,  3, CO, 17, 0x000001u, 0x000041u }, // ldc.l @<REG_N>+,SSR
	{ 0xF0FF, 0x4047, 1,  3, CO, 17, 0x000001u, 0x000081u }, // ldc.l @<REG_N>+,SPC
	{ 0xF08F, 0x4087, 1,  3, CO, 17, 0x000001u, 0x000009u }, // ldc.l @<REG_N>+,RM_BANK
	{ 0xF0FF, 0x0002, 2,  2, CO, 20, 0x000020u, 0x000001u }, // stc SR,<REG_N>
	{ 0xF0FF, 0x0012, 2,  2, CO, 20, 0x000010u, 0x000001u }, // stc GBR,<REG_N>
	{ 0xF0FF, 0x0022, 2,  2, CO, 20, 0x000100u, 0x000001u }, // stc VBR,<REG_N>
	{ 0xF0FF, 0x0032, 2,  2, CO, 20, 0x000040u, 0x000001u }, // stc SSR,<REG_N>
	{ 0xF0FF, 0x0042, 2,  2, CO, 20, 0x000080u, 0x000001u }, // stc SPC,<REG_N>
	{ 0xF08F, 0x0082, 2,  2, CO, 20, 0x000008u, 0x000001u }, // stc RM_BANK,<REG_N>
	{ 0xF0FF, 0x000A, 1,  3, CO, 30, 0x001000u, 0x000001u }, // sts MACH,<REG_N>
	{ 0xF0FF, 0x001A, 1,  3, CO, 30, 0x002000u, 0x000001u }, // sts MACL,<REG_N>
	{ 0xF0FF, 0x002A, 2,  2, CO, 26, 0x000800u, 0x000001u }, // sts PR,<REG_N>
	{ 0xF0FF, 0x003A, 3,  3, CO, 21, 0x000400u, 0x000001u }, // sts SGR,<REG_N>
	{ 0xF0FF, 0x005A, 1,  3, LS,  1, 0x004000u, 0x000001u }, // sts FPUL,<REG_N>
	{ 0xF0FF, 0x006A, 1,  3, CO,  1, 0x008000u, 0x000001u }, // sts FPSCR,<REG_N>
	{ 0xF0FF, 0x00FA, 2,  2, CO, 20, 0x000200u, 0x000001u }, // sts DBR,<REG_N>
	{ 0xF0FF, 0x400A, 1,  3, CO, 28, 0x000001u, 0x001000u }, // lds <REG_N>,MACH
	{ 0xF0FF, 0x401A, 1,  3, CO, 28, 0x000001u, 0x002000u }, // lds <REG_N>,MAC
	{ 0xF0FF, 0x402A, 2,  3, CO, 24, 0x000001u, 0x000800u }, // lds <REG_N>,PR
	{ 0xF0FF, 0x403A, 3,  3, CO, 15, 0x000001u, 0x000400u }, // ldc <REG_N>,SGR
	{ 0xF0FF, 0x405A, 1,  1, LS,  1, 0x000001u, 0x004000u }, // lds <REG_N>,FPUL
	{ 0xF0FF, 0x406A, 1,  4, CO, 32, 0x000001u, 0x008000u }, // lds <REG_N>,FPSCR
	{ 0xF0FF, 0x40FA, 1,  3, CO, 14, 0x000001u, 0x000200u }, // ldc <REG_N>,DBR
	{ 0xF0FF, 0x400E, 4,  4, CO, 16, 0x000001u, 0x000020u }, // ldc <REG_N>,SR
	{ 0xF0FF, 0x401E, 3,  3, CO, 15, 0x000001u, 0x000010u }, // ldc <REG_N>,GBR
	{ 0xF0FF, 0x402E, 1,  3, CO, 14, 0x000001u, 0x000100u }, // ldc <REG_N>,VBR
	{ 0xF0FF, 0x403E, 1,  3, CO, 14, 0x000001u, 0x000040u }, // ldc <REG_N>,SSR
	{ 0xF0FF, 0x404E, 1,  3, CO, 14, 0x000001u, 0x000080u }, // ldc <REG_N>,SPC
	{ 0xF08F, 0x408E, 1,  3, CO, 14, 0x000001u, 0x000008u }, // ldc <REG_N>,<RM_BANK>
	{ 0xF0FF, 0x4000, 1,  1, EX,  1, 0x000001u, 0x010001u }, // shll <REG_N>
	{ 0xF0FF, 0x4010, 1,  1, EX,  1, 0x000001u, 0x010001u }, // dt <REG_N>
	{ 0xF0FF, 0x4020, 1,  1, EX,  1, 0x000001u, 0x010001u }, // shal <REG_N>
	{ 0xF0FF, 0x4001, 1,  1, EX,  1, 0x000001u, 0x010001u }, // shlr <REG_N>
	{ 0xF0FF, 0x4011, 1,  1, MT,  1, 0x000001u, 0x010000u }, // cmp/pz <REG_N>
	{ 0xF0FF, 0x4021, 1,  1, EX,  1, 0x000001u, 0x010001u }, // shar <REG_N>
	{ 0xF0FF, 0x4024, 1,  1, EX,  1, 0x010001u, 0x010001u }, // rotcl <REG_N>
	{ 0xF0FF, 0x4004, 1,  1, EX,  1, 0x000001u, 0x010001u }, // rotl <REG_N>
	{ 0xF0FF, 0x4015, 1,  1, MT,  1, 0x000001u, 0x010000u }, // cmp/pl <REG_N>
	{ 0xF0FF, 0x4025, 1,  1, EX,  1, 0x010001u, 0x010001u }, // rotcr <REG_N>
	{ 0xF0FF, 0x4005, 1,  1, EX,  1, 0x000001u, 0x010001u }, // rotr <REG_N>
	{ 0xF0FF, 0x4008, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shll2 <REG_N>
	{ 0xF0FF, 0x4018, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shll8 <REG_N>
	{ 0xF0FF, 0x4028, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shll16 <REG_N>
	{ 0xF0FF, 0x4009, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shlr2 <REG_N>
	{ 0xF0FF, 0x4019, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shlr8 <REG_N>
	{ 0xF0FF, 0x4029, 1,  1, EX,  1, 0x000001u, 0x000001u }, // shlr16 <REG_N>
	{ 0xF0FF, 0x402B, 2,  3, CO,  4, 0x000001u, 0x000000u }, // jmp @<REG_N>
	{ 0xF0FF, 0x400B, 2,  3, CO, 24, 0x000001u, 0x000000u }, // jsr @<REG_N>
	{ 0xF0FF, 0x401B, 5,  5, CO,  7, 0x000001u, 0x010000u }, // tas.b @<REG_N>
	{ 0xF00F, 0x400C, 1,  1, EX,  1, 0x000003u, 0x000001u }, // shad <REG_M>,<REG_N>
	{ 0xF00F, 0x400D, 1,  1, EX,  1, 0x000003u, 0x000001u }, // shld <REG_M>,<REG_N>
	{ 0xF00F, 0x400F, 2,  4, CO, 35, 0x000003u, 0x003003u }, // mac.w @<REG_M>+,@<REG_N>+
	{ 0xF00F, 0x6007, 1,  1, EX,  1, 0x000002u, 0x000001u }, // not <REG_M>,<REG_N>
	{ 0xF00F, 0x6008, 1,  1, EX,  1, 0x000002u, 0x000001u }, // swap.b <REG_M>,<REG_N>
	{ 0xF00F, 0x6009, 1,  1, EX,  1, 0x000002u, 0x000001u }, // swap.w <REG_M>,<REG_N>
	{ 0xF00F, 0x600A, 1,  1, EX,  1, 0x010002u, 0x010001u }, // negc <REG_M>,<REG_N>
	{ 0xF00F, 0x600B, 1,  1, EX,  1, 0x000002u, 0x000001u }, // neg <REG_M>,<REG_N>
	{ 0xF00F, 0x600C, 1,  1, EX,  1, 0x000002u, 0x000001u }, // extu.b <REG_M>,<REG_N>
	{ 0xF00F, 0x600D, 1,  1, EX,  1, 0x000002u, 0x000001u }, // extu.w <REG_M>,<REG_N>
	{ 0xF00F, 0x600E, 1,  1, EX,  1, 0x000002u, 0x000001u }, // exts.b <REG_M>,<REG_N>
	{ 0xF00F, 0x600F, 1,  1, EX,  1, 0x000002u, 0x000001u }, // exts.w <REG_M>,<REG_N>
	{ 0xF000, 0x7000, 1,  1, EX,  1, 0x000001u, 0x000001u }, // add #<simm8>,<REG_N>
	{ 0xFF00, 0x8B00, 1,  2, BR,  1, 0x010000u, 0x000000u }, // bf <bdisp8>
	{ 0xFF00, 0x8F00, 1,  2, BR,  1, 0x010000u, 0x000000u }, // bf.s <bdisp8>
	{ 0xFF00, 0x8900, 1,  2, BR,  1, 0x010000u, 0x000000u }, // bt <bdisp8>
	{ 0xFF00, 0x8D00, 1,  2, BR,  1, 0x010000u, 0x000000u }, // bt.s <bdisp8>
	{ 0xFF00, 0x8800, 1,  1, MT,  1, 0x000004u, 0x010000u }, // cmp/eq #<simm8hex>,R0
	{ 0xF000, 0xA000, 1,  2, BR,  1, 0x000000u, 0x000000u }, // bra <bdisp12>
	{ 0xF000, 0xB000, 1,  2, BR, 14, 0x000000u, 0x000000u }, // bsr <bdisp12>
	{ 0xFF00, 0xC300, 7,  7, CO, 13, 0x000000u, 0x000000u }, // trapa #<imm8>
	{ 0xFF00, 0xC800, 1,  1, MT,  1, 0x000004u, 0x010000u }, // tst #<imm8>,R0
	{ 0xFF00, 0xC900, 1,  1, EX,  1, 0x000004u, 0x000004u }, // and #<imm8>,R0
	{ 0xFF00, 0xCA00, 1,  1, EX,  1, 0x000004u, 0x000004u }, // xor #<imm8>,R0
	{ 0xFF00, 0xCB00, 1,  1, EX,  1, 0x000004u, 0x000004u }, // or #<imm8>,R0
	{ 0xFF00, 0xCC00, 3,  3, CO,  5, 0x000014u, 0x010000u }, // tst.b #<imm8>,@(R0,GBR)
	{ 0xFF00, 0xCD00, 4,  4, CO,  6, 0x000014u, 0x000000u }, // and.b #<imm8>,@(R0,GBR)
	{ 0xFF00, 0xCE00, 4,  4, CO,  6, 0x000014u, 0x000000u }, // xor.b #<imm8>,@(R0,GBR)
	{ 0xFF00, 0xCF00, 4,  4, CO,  6, 0x000014u, 0x000000u }, // or.b #<imm8>,@(R0,GBR)
	{ 0xF00F, 0xF000, 1,  4, FE, 36, 0x060000u, 0x020000u }, // fadd <FREG_M_SD_F>,<FREG_N>
	{ 0xF00F, 0xF001, 1,  4, FE, 36, 0x060000u, 0x020000u }, // fsub <FREG_M_SD_F>,<FREG_N>
	{ 0xF00F, 0xF002, 1,  4, FE, 36, 0x060000u, 0x020000u }, // fmul <FREG_M_SD_F>,<FREG_N>
	{ 0xF00F, 0xF003, 1, 13, FE, 37, 0x060000u, 0x020000u }, // fdiv <FREG_M_SD_F>,<FREG_N>
	{ 0xF00F, 0xF004, 1,  4, FE, 36, 0x060000u, 0x010000u }, // fcmp/eq <FREG_M>,<FREG_N>
	{ 0xF00F, 0xF005, 1,  4, FE, 36, 0x060000u, 0x010000u }, // fcmp/gt <FREG_M>,<FREG_N>
	{ 0xF00F, 0xF006, 1,  2, LS,  2, 0x000006u, 0x020000u }, // fmov.s @(R0,<REG_M>),<FREG_N>
	{ 0xF00F, 0xF007, 1,  1, LS,  2, 0x040005u, 0x000000u }, // fmov.s <FREG_M>,@(R0,<REG_N>)
	{ 0xF00F, 0xF008, 1,  2, LS,  2, 0x000002u, 0x020000u }, // fmov.s @<REG_M>,<FREG_N>
	{ 0xF00F, 0xF009, 1,  2, LS,  2, 0x000002u, 0x020002u }, // fmov.s @<REG_M>+,<FREG_N>
	{ 0xF00F, 0xF00A, 1,  1, LS,  2, 0x040001u, 0x000000u }, // fmov.s <FREG_M>,@<REG_N>
	{ 0xF00F, 0xF00B, 1,  1, LS,  2, 0x040001u, 0x000001u }, // fmov.s <FREG_M>,@-<REG_N>
	{ 0xF00F, 0xF00C, 1,  0, LS,  1, 0x040000u, 0x020000u }, // fmov <FREG_M>,<FREG_N>
	{ 0xF0FF, 0xF05D, 1,  0, LS,  1, 0x020000u, 0x020000u }, // fabs <FREG_N>
	{ 0xF1FF, 0xF0FD, 1,  3, FE, 44, 0x004000u, 0x100000u }, // FSCA FPUL, <DR_N>
	{ 0xF0FF, 0xF0BD, 1,  4, FE, 38, 0x100000u, 0x004000u }, // fcnvds <DR_N>,FPUL
	{ 0xF0FF, 0xF0AD, 1,  4, FE, 38, 0x004000u, 0x100000u }, // fcnvsd FPUL,<DR_N>
	{ 0xF0FF, 0xF0ED, 1,  5, FE, 42, 0x600000u, 0x200000u }, // fipr <FV_M>,<FV_N>
	{ 0xF0FF, 0xF08D, 1,  0, LS,  1, 0x000000u, 0x020000u }, // fldi0 <FREG_N>
	{ 0xF0FF, 0xF09D, 1,  0, LS,  1, 0x000000u, 0x020000u }, // fldi1 <FREG_N>
	{ 0xF0FF, 0xF01D, 1,  0, LS,  1, 0x020000u, 0x004000u }, // flds <FREG_N>,FPUL
	{ 0xF0FF, 0xF02D, 1,  4, FE, 36, 0x004000u, 0x020000u }, // float FPUL,<FREG_N>
	{ 0xF0FF, 0xF04D, 1,  0, LS,  1, 0x020000u, 0x020000u }, // fneg <FREG_N> 
	{ 0xFFFF, 0xFBFD, 1,  4, FE, 36, 0x000000u, 0x008000u }, // frchg
	{ 0xFFFF, 0xF3FD, 1,  4, FE, 36, 0x000000u, 0x008000u }, // fschg
	{ 0xF0FF, 0xF06D, 1, 23, FE, 41, 0x020000u, 0x020000u }, // fsqrt <FREG_N>
	{ 0xF0FF, 0xF03D, 1,  4, FE, 38, 0x020000u, 0x004000u }, // ftrc <FREG_N>, FPUL
	{ 0xF0FF, 0xF00D, 1,  0, LS,  1, 0x004000u, 0x020000u }, // fsts FPUL,<FREG_N>
	{ 0xF3FF, 0xF1FD, 1,  8, FE, 43, 0xA00000u, 0x200000u }, // ftrv xmtrx,<FV_N>
	{ 0xF00F, 0xF00E, 1,  4, FE, 36, 0x0E0000u, 0x020000u }, // fmac <FREG_0>,<FREG_M>,<FREG_N>
	{ 0xF0FF, 0xF07D, 1,  4, FE, 36, 0x020000u, 0x020000u }, // FSRRA <FREG_N>
};
static const size_t opInfoTableSize = sizeof(opInfoTable) / sizeof(opInfoTable[0]);

}
