#!/usr/bin/env python3
"""Generate a Dreamcast program that measures the corpus on real hardware.

The point of this is to stop the JS simulator being the arbiter. It is a second
model, not a measurement, and two models agreeing says only that they were
written from the same manual.

Method. Each block is emitted twice, unrolled M and 2M times, and the per-block
cost is taken as the difference divided by M. That cancels the prologue, the
loop overhead and the counter read entirely, so nothing has to be modelled or
subtracted afterwards.

Per the SH-4 ABI, FR12-FR15 are callee-save and are saved and restored here.
The first version of this did not, and the FP probe corrupted the doubles the
measuring code was holding in exactly those registers - the results came back
as inf. FR0-FR11 are caller-save (return value and parameter passing) and so
are free to clobber, as is FPUL. The frchg pair below leaves FPSCR.FR back at
zero, which the ABI requires at entry and exit.

Registers are pointed at a small scratch buffer that stays inside the operand
cache, so loads and stores hit. The icache and dcache pipeline-freeze counters
are reported alongside every result specifically so that assumption is checked
rather than assumed - if they are not near zero the block's cycle figure is
measuring memory, not the pipeline, and is excluded.

Blocks must be generated with --dense so they only touch r0-r3 and fr0-fr3;
the prologue initialises exactly those, plus GBR, and saves what the body can
clobber.
"""
import argparse, os, re, sys

# Events to sample. PRFC0 always holds elapsed cycles; PRFC1 rotates through
# these across passes, since the SH4 only has two counters.
EVENTS = [
    ("PMCR_INSTRUCTION_ISSUED_MODE",              "issued"),
    ("PMCR_PARALLEL_INSTRUCTION_ISSUED_MODE",     "parallel"),
    ("PMCR_PIPELINE_FREEZE_BY_CPU_REGISTER_MODE", "frz_reg"),
    ("PMCR_PIPELINE_FREEZE_BY_FPU_MODE",          "frz_fpu"),
    ("PMCR_PIPELINE_FREEZE_BY_ICACHE_MISS_MODE",  "frz_ic"),
    ("PMCR_PIPELINE_FREEZE_BY_DCACHE_MISS_MODE",  "frz_dc"),
]

PROLOGUE = """\t.align 2
\t.global _{name}
_{name}:
\tsts.l pr,@-r15
\tstc.l gbr,@-r15
\tmov.l r8,@-r15
\tfmov.s fr12,@-r15
\tfmov.s fr13,@-r15
\tfmov.s fr14,@-r15
\tfmov.s fr15,@-r15
\tmov r4,r8
\tldc r4,gbr
\tmov r4,r0
\tmov r4,r1
\tmov r4,r2
\tmov r4,r3
\tfldi1 fr0
\tfldi1 fr1
\tfldi1 fr2
\tfldi1 fr3
"""

EPILOGUE = """\tfmov.s @r15+,fr15
\tfmov.s @r15+,fr14
\tfmov.s @r15+,fr13
\tfmov.s @r15+,fr12
\tmov.l @r15+,r8
\tldc.l @r15+,gbr
\tlds.l @r15+,pr
\trts
\tnop

"""

def blocks_of(path):
    txt = open(path).read()
    parts = re.split(r'(?m)^(#.*)$', txt)
    out = []
    for i in range(1, len(parts), 2):
        body = [l.strip() for l in parts[i + 1].split('\n') if l.strip()]
        if body:
            out.append(body)
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("corpus")
    ap.add_argument("outdir")
    ap.add_argument("--unroll", type=int, default=32)
    ap.add_argument("--iters", type=int, default=64)
    args = ap.parse_args()

    blocks = blocks_of(args.corpus)
    os.makedirs(args.outdir, exist_ok=True)
    M = args.unroll

    # Every block appears at two unroll depths; the difference is the answer.
    asm = ["\t.little\n\t.text\n"]
    for i, b in enumerate(blocks):
        for mult, suffix in ((1, "a"), (2, "b")):
            asm.append(PROLOGUE.format(name="blk%d%s" % (i, suffix)))
            for _ in range(M * mult):
                asm.extend("\t" + ins + "\n" for ins in b)
            asm.append(EPILOGUE)
    open(os.path.join(args.outdir, "blocks.s"), "w").write("".join(asm))

    decls = "\n".join("void blk%da(void *);\nvoid blk%db(void *);" % (i, i)
                      for i in range(len(blocks)))
    table = ",\n".join("    { blk%da, blk%db }" % (i, i) for i in range(len(blocks)))
    evnames = ",\n".join('    { %s, "%s" }' % (e, n) for e, n in EVENTS)

    c = r'''/* Generated by tools/pipesim/gen_hwtest.py - do not edit. */
#include <kos.h>
#include <dc/perfctr.h>
#include <arch/cache.h>
#include <stdio.h>
#include <stdlib.h>

#define NBLOCKS %(nblocks)d
#define UNROLL  %(unroll)d
#define ITERS   %(iters)d

%(decls)s

typedef void (*blockfn)(void *);
static const struct { blockfn a, b; } blocks[NBLOCKS] = {
%(table)s
};

static const struct { int mode; const char *name; } events[] = {
%(evnames)s
};
#define NEVENTS ((int)(sizeof(events) / sizeof(events[0])))

/* Small enough to stay resident in the 16K operand cache, so that loads and
   stores in the measured blocks hit.

   Only r3 addresses memory, and the hardware-safe vocabulary never writes r3,
   so no block can turn loaded data into an address. GBR points here too, and
   GBR displacements are at most 255, so those stay inside as well.

   The buffer is still filled with a pointer to itself rather than left as
   zeroes: it costs nothing, and it means a form that slips through the
   vocabulary filter faults on a wild address far less often. */
static unsigned char scratch[8192] __attribute__((aligned(32)));

static uint64 measure(blockfn fn, void *arg, int event, uint64 *ev_out) {
    uint64 best_cyc = ~0ull, best_ev = 0;

    for(int it = 0; it < ITERS; it++) {
        perf_cntr_clear(PRFC0);
        perf_cntr_clear(PRFC1);
        perf_cntr_start(PRFC0, PMCR_ELAPSED_TIME_MODE, PMCR_COUNT_CPU_CYCLES);
        perf_cntr_start(PRFC1, event, PMCR_COUNT_CPU_CYCLES);
        fn(arg);
        perf_cntr_stop(PRFC0);
        perf_cntr_stop(PRFC1);

        uint64 c = perf_cntr_count(PRFC0);
        /* Minimum, not mean: anything above it is interference from something
           this test does not control, and there is no such thing as a run that
           was accidentally too fast. */
        if(c < best_cyc) { best_cyc = c; best_ev = perf_cntr_count(PRFC1); }
    }
    *ev_out = best_ev;
    return best_cyc;
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;
    void *arg = &scratch[2048];

    for(size_t i = 0; i < sizeof(scratch) / sizeof(uint32); i++)
        ((uint32 *)scratch)[i] = (uint32)(uintptr_t)arg;

    printf("# pipesim hardware measurement\n");
    printf("# unroll=%%d iters=%%d\n", UNROLL, ITERS);
    printf("# per-block cost = (cycles(2M) - cycles(M)) / M, M=%%d\n", UNROLL);
    printf("block\tcycles");
    for(int e = 0; e < NEVENTS; e++) printf("\t%%s", events[e].name);
    printf("\n");

    for(int i = 0; i < NBLOCKS; i++) {
        double cyc = 0;
        double evs[NEVENTS];

        for(int e = 0; e < NEVENTS; e++) {
            uint64 ea = 0, eb = 0;
            /* Warm the caches for this block before it is measured. */
            blocks[i].a(arg);
            blocks[i].b(arg);

            uint64 ca = measure(blocks[i].a, arg, events[e].mode, &ea);
            uint64 cb = measure(blocks[i].b, arg, events[e].mode, &eb);

            if(e == 0) cyc = (double)((int64)cb - (int64)ca) / UNROLL;
            evs[e] = (double)((int64)eb - (int64)ea) / UNROLL;
        }

        printf("%%d\t%%.3f", i, cyc);
        for(int e = 0; e < NEVENTS; e++) printf("\t%%.3f", evs[e]);
        printf("\n");
        fflush(stdout);
    }

    printf("# done\n");
    return 0;
}
''' % dict(nblocks=len(blocks), unroll=M, iters=args.iters,
           decls=decls, table=table, evnames=evnames)
    open(os.path.join(args.outdir, "main.c"), "w").write(c)

    mk = """TARGET = pipehw.elf
OBJS = main.o blocks.o

all: rm-elf $(TARGET)

include $(KOS_BASE)/Makefile.rules

clean: rm-elf
\t-rm -f $(OBJS)

rm-elf:
\t-rm -f $(TARGET)

$(TARGET): $(OBJS)
\tkos-cc -o $(TARGET) $(OBJS)

run: $(TARGET)
\t$(KOS_LOADER) $(TARGET)
"""
    open(os.path.join(args.outdir, "Makefile"), "w").write(mk)
    print("wrote %d blocks to %s (%d asm functions)" % (len(blocks), args.outdir, len(blocks) * 2))

main()
